### ISSUE TITLE
Transfer to official Dracula org

### ISSUE THREAD

**Issue by zenorocha** [dracula/telegram-ios#1]
Hey Enrico!

A Dracula fan just told me about your Telegram theme for iOS. Good job by the way!

I was wondering if you are interested in transferring this repository to the official organization (https://github.com/dracula). You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

What do you think?

**Comment by enricobez** [comment]
Hi Zeno,
I'm glad that you appreciate my work and yes, why not! Let's transfer it to the official repo.

**Comment by zenorocha** [comment]
Great! I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by zenorocha** [comment]
https://draculatheme.com/telegram-ios 💥 💥 💥
