### ISSUE TITLE
Standardize repository

### ISSUE THREAD

**Issue by zenorocha** [dracula/telegram-ios#2]
Hey @enricobez, in order to add it to the site and standardize with the other repos, there are a couple of  things we'll need to do:

- [x] Rename repo to `telegram-ios`
- [x] Move screenshot files to root folder
- [x] Rename main screenshot file to `screenshot.png` (that way it can be picked up by the site)
- [x] Update LICENSE - https://github.com/dracula/template/blob/master/LICENSE
- [x] Create a INSTALL.md (needed for the site) - https://github.com/dracula/template/blob/master/INSTALL.md
- [x] Update repo about section - https://share.getcloudapp.com/p9ur1qRK

Reference: https://github.com/dracula/template

**Comment by zenorocha** [comment]
https://github.com/dracula/telegram-ios/commit/faf6dc2ad4a910745d7ffebfde66957da1c08604

**Comment by enricobez** [comment]
Thanks!
